//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"C:\\Users\\Smart\\Desktop\\Mathe" +
            "w deans examples\\MS Watch Shop Master Final final final final final\\MSWatchShop\\" +
            "MSWatchShop\\App_Data\\MSWatchShopCustomer.MDF\";Integrated Security=True;Connect T" +
            "imeout=30")]
        public string MSWatchShopCustomerConnectionString {
            get {
                return ((string)(this["MSWatchShopCustomerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"C:\\Users\\Smart\\Desktop\\Mathe" +
            "w deans examples\\MS Watch Shop Master Final final final final final\\MSWatchShop\\" +
            "MSWatchShop\\App_Data\\MSWatchShopProduct.MDF\";Integrated Security=True;Connect Ti" +
            "meout=30")]
        public string MSWatchShopProductConnectionString {
            get {
                return ((string)(this["MSWatchShopProductConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=""C:\Users\Smart\Desktop\Final Project Work\Game Geek Finalllllllllllllllllllllllllllllllllllllllllllllllllllllllll\GameGeek\GameGeekFrontEnd\App_Data\GameGeekCustomer.MDF"";Integrated Security=True;Connect Timeout=30")]
        public string GameGeekCustomerConnectionString {
            get {
                return ((string)(this["GameGeekCustomerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=""C:\Users\Smart\Desktop\Final Project Work\Game Geek Finalllllllllllllllllllllllllllllllllllllllllllllllllllllllll\GameGeek\GameGeekFrontEnd\App_Data\GameGeekProduct.MDF"";Integrated Security=True;Connect Timeout=30")]
        public string GameGeekProductConnectionString {
            get {
                return ((string)(this["GameGeekProductConnectionString"]));
            }
        }
    }
}
